import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { type RouterOutputs, api } from "~/utils/api";

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithAuthor) => {
  const { post, author } = props;
  return (
    <div className="p-6">
      <Image
        src={author.profileImageUrl}
        className="h-10 w-10 rounded-full"
        alt="Profile picture"
      />
      <p>{post.content}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();
  console.log(user);

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Failed to load posts</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center">
        <div className="flex h-full w-full flex-col divide-y divide-pink-400 border-x-2 border-pink-400 bg-pink-600 md:max-w-2xl">
          <div className="flex w-full p-4">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && (
              <div className="flex w-full items-center gap-2">
                <UserButton />
                <input
                  type="text"
                  placeholder="Type some emojis"
                  className="w-full rounded-lg border-2 border-pink-400 bg-transparent p-2 outline-none"
                />
              </div>
            )}
          </div>
          {data.map(({ post, author }) => (
            <PostView key={post.id} post={post} author={author} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
